image: docker:latest

include:
    - project: 'rdbioseq/cd/cd-environment-module'
      file: '/cd-environment-module.yml'

workflow:
    rules:
        - if: $CI_COMMIT_TAG == null

variables:
    GIT_STRATEGY           : clone
    docker_tag             : $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CDENVMOD_RUNDECK_TOKEN : $RDBIOSEQ_RUNDECK_TOKEN
    CDENVMOD_TEAM          : 'rdbioseq'
    CDENVMOD_MODULE        : 'fastoche'
    CDENVMOD_PROJECT       : $CI_PROJECT_ID
    CDENVMOD_COMMIT        : $CI_COMMIT_SHA

.docker_stage:
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    after_script:
        - docker logout $CI_REGISTRY

stages: 
    - build
    - test
    - cd_environment_module

Build:
    stage: build
    tags:
        - docker_build
    extends:
        - .docker_stage
    script:
        - docker build -t $docker_tag .
        - docker push $docker_tag

Test:
    stage: test
    tags:
        - docker_build
    extends:
        - .docker_stage
    script: 
        - docker pull $docker_tag
        - docker run $docker_tag bash -c "cargo test"
