include:
  - project: rdbioseq/cicd
    file: cicd.yml
    inputs:
      module-name: "fastoche"
      module-snapshot: true
      other-branches-as-named: true

stages: 
  - deploy

deploy:
  stage: deploy
  extends: .deploy

deploy-futur:
    stage: deploy
    extends: .deploy-futur
