[package]
name = "fastoche"
version = "0.1.0"
edition = "2021"
authors = ["bistace"]


[dependencies]
clap = { version = "4", features = ["derive"] }
flate2 = "1.0.25"
needletail = "0.5.0"
tabled = {version = "0.10.0", features = ["color"]}
thousands = "0.2.0"
